### ISSUE TITLE
Issues with hookActionOrderGridDefinitionModifier

### ISSUE THREAD

**Issue by econtentsys** [wallee-payment/prestashop-1.7#3]
The hookActionOrderGridDefinitionModifier calls some functions that don't exist 
like getOptionId() and add()
Problem found in Prestashop 1.7.7.1. "sell/orders" page doesn't work because of that.
Disabling hookActionOrderGridDefinitionModifier in wallee.php bypasses the problem

**Comment by theodorspringwallee** [comment]
Dear [econtentsys](https://github.com/econtentsys)

Sorry for the late response.

According to our devs this issue should be solved in the meanwhile. 
To be sure you just can install the newest plugin version.
